---

- ansible.builtin.include_tasks: init.yml

- name: Download the ErsatzTV archive
  register: etv_archive
  until: 'etv_archive is not failed'
  retries: 3
  delay: 5
  ansible.builtin.unarchive:
    src: "{{ _ersatztv_repo }}/releases/download/{{ etv_version }}/ErsatzTV-{{ etv_version }}-linux-x64.tar.gz"
    dest: "{{ _ersatztv_download_path }}"
    remote_src: true
    list_files: true
    creates: "{{ _ersatztv_download_path }}/ErsatzTV-{{ etv_version }}-linux-x64"

- name: Download the latest ffmpeg archive
  register: etv_ffmpeg_archive
  until: 'etv_ffmpeg_archive is not failed'
  retries: 3
  delay: 5
  ansible.builtin.get_url:
    url: "{{ _ersatztv_ffmpeg_url }}"
    dest: "{{ _ersatztv_download_path }}"
    decompress: false
