---

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: "localhost/docker-almalinux9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    nocache: true
    published_ports:
      - 8409:8409/tcp

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
